### ISSUE TITLE
Why are scene headings underlined though?

### ISSUE THREAD

**Issue by chariegg** [qxoko/meander#6]
This is a pretty cool little doodad you got here. I may donate in the future, but one confusion I have is that: why does it underline scene headings like from (for example) the Big Fish one from https://www.fountain.io/syntax website.

[BigFishy.pdf](https://github.com/qxoko/meander/files/14096988/BigFishy.pdf)

I used your program to render the Big-Fish.fountain file to BigFishy.pdf, but I'm puzzled why the scene headings are underlined. Never seen any other converter or render program do that. So I'm more puzzled and confused if anything. Additionally, I want to comment on the fdx converter support, I didn't think this warranted a new issue thread, so I'll mention it here:

You can use writersolo.com to convert fountain files to fdx to see how the syntax changes in the xml markup. If I could make a suggestion, you could just have the converter completely omit stuff that would be only for final draft users only like page locking and stuff like that. Just ignore it and focus on the elements that would be practical for plain text editing like fountain in vim or emacs.

**Comment by qxoko** [comment]
As to the scene headings, it was an aesthetic choice I preferred.  Various tools will make the scene headings stand out in different ways because they're an important element — Highland, for instance, makes them bold.  I agree with them that scene headings don't stand out enough on physical, printed page, so I chose to underline them.

If you've ever been stood in a rainy field trying to parse a shooting script or cross-reference it with your setup list, you'll know why this matters.

Also, it's trivial to edit this in `template.go` if you _really_ don't like it.

---

As for Final Draft conversion, Meander's priority is **reading** FDX files rather than creating them.  Final Draft itself can import core specification Fountain, so there's not a huge reason to do it right now.

I just mentioned offhandedly in the readme that Meander _could_ support exporting to FDX if there was enough demand.  There's something to be said for being a self-contained Swiss-Army knife in that way. Meander's syntax extensions could benefit from a dedicated FDX exporter so it can translate everything in a single step, but they're not significant enough that this matters right now.  In the meantime, I have a middle-ground solution that I'll be implementing first, which is outlined in #3

Also when I say I need to be aware of Final Draft-specific features, I'm referring to Meander's **reader**.  It has to be able to _read_ all possible permutations of Final Draft's XML structure so it doesn't crash or produce garbage output.  Right now, it supports reading 'basic' FD files because those are what I have access to.
